name = "KinematicConstraintGraphs"
uuid = "7ccb7bd5-4b2d-4ee4-a25e-22e0cc1164c1"
authors = ["Sascha Stüttgen <sascha.steuttgen@rwth-aachen.de> and contributors"]
version = "1.0.0-DEV"

[deps]
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
